# Kind 集群配置
# 单控制平面 + 单 Worker，开放 dlv 调试端口
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: k8s-debug

nodes:
  - role: control-plane
    image: kindest/node:local-debug

    extraMounts:
      - hostPath: /tmp/k8s-debug-bins
        containerPath: /debug-bins
        readOnly: false
      - hostPath: /tmp/k8s-debug-src
        containerPath: /debug-src
        readOnly: true

    # dlv headless 调试端口
    extraPortMappings:
      - containerPort: 2345   # kube-apiserver
        hostPort: 2345
        protocol: TCP
      - containerPort: 2346   # kube-controller-manager
        hostPort: 2346
        protocol: TCP
      - containerPort: 2347   # kube-scheduler
        hostPort: 2347
        protocol: TCP
      - containerPort: 2348   # kubelet
        hostPort: 2348
        protocol: TCP
      - containerPort: 2349   # kube-proxy
        hostPort: 2349
        protocol: TCP
      - containerPort: 2350   # containerd
        hostPort: 2350
        protocol: TCP

    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            allow-privileged: "true"

  - role: worker
    image: kindest/node:local-debug
    extraMounts:
      - hostPath: /tmp/k8s-debug-bins
        containerPath: /debug-bins
        readOnly: false
